### ISSUE TITLE
Server error on restart after I add a site icon

### ISSUE THREAD

**Issue by blazer82** [LemmyNet/lemmy-ui#1765]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

After adding a site icon I cannot restart the Docker container anymore because it would just crash and log this:

```
Node.js v20.3.1
Inferno is in development mode.
http://0.0.0.0:1234
Error: Input bit Array is empty
    at Sharp._createInputDescriptor (/app/node_modules/sharp/lib/input.js:56:13)
    at new Sharp (/app/node_modules/sharp/lib/constructor.js:350:29)
    at Sharp (/app/node_modules/sharp/lib/constructor.js:173:12)
    at /app/dist/js/server.js:2:1144276
    at tryCatch (/app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (/app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
    at Generator.next (/app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Input bit Array is empty
    at Sharp._createInputDescriptor (/app/node_modules/sharp/lib/input.js:56:13)
    at new Sharp (/app/node_modules/sharp/lib/constructor.js:350:29)
    at Sharp (/app/node_modules/sharp/lib/constructor.js:173:12)
    at /app/dist/js/server.js:2:1144276
    at tryCatch (/app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (/app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
    at Generator.next (/app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
…
```

Manually removing the icon from the site in the database did help.

I verified that the site icon URL is a valid URL and can be accessed (the site icon did display after adding it after all).

### Steps to Reproduce

1. Add site icon
2. Restart docker compose
3. Try to access the UI --> Server error
4. Remove the site icon
5. Try to access the UI --> works again

### Technical Details

docker-compose setup with dessalines/lemmy-ui:0.18.0 on Amazon Linux 2 AMI (also tried with dessalines/lemmy-ui:0.18.1-rc.4)

### Lemmy Instance Version

0.18.0

**Comment by blazer82** [comment]
I just noticed there may be an issue with my pictrs setup after all. The image that was accessible at some point now isn't anymore. I'll update here if I find out more. And it would still be nice if the UI wouldn't just crash because of this.

**Comment by blazer82** [comment]
Updated to dessalines/lemmy-ui:0.18.1-rc.7 and tried image uploads for posts and icons. Seems to be working. Not restarted the docker container yet but so far so good.

**Comment by blazer82** [comment]
Okay, another bit of information: I've been running multiple instances of the docker setup behind a load balancer and although I'm using an S3 backend for pictrs, it's may understanding that pictrs isn't entirely stateless which may have caused the issues with the uploaded images.

Nonetheless, it would probably be good if the UI didn't crash on startup just because of broken images.

**Comment by blazer82** [comment]
So, I got the pictrs issues under control on my side and most likely won't be experiencing this crash anymore. I'm gonna close this issue here even though I still think this needs improvement lemmy-ui's side.

Also, someone might find this some day and it may be helpful to them.

**Comment by jivandabeast** [comment]
How were you able to remove the site icon if you can't access the Lemmy UI? I have the same issue you do now lol

**Comment by blazer82** [comment]
Yeah, my lemmy is crashing again because of issues with pictrs. This thing not being stateless is really giving me a headache.

**Comment by jivandabeast** [comment]
Hmm, upon closer inspection I think our two issues are separate. It looks like somewhere along the way my setup is not returning images. I can see them being uploaded to pictrs but the link for it on lemmy returns a 404...

Hope you get your issue sorted though!

**Comment by JM1705** [comment]
I think I might be having a similar issue.

The error I'm getting from lemmy-ui is:
`FetchError: request to https://<my lemmy domain>/pictrs/image/6973ae27-9d83-4e77-8a2e-d65116e345c1.png failed, reason: getaddrinfo EAI_AGAIN <my lemmy domain>
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1505:11)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'
}
`

I also reverted this server from a backup image, so that could also be the problem though.
