### ISSUE TITLE
Sopuli's (only?) Webapp crash after installing via FF based browser

### ISSUE THREAD

**Issue by TalOrenshtein** [LemmyNet/lemmy-ui#1827]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

When trying to use webview version of sopuli, the wv crashes instantly, but, at lemmy.world or lemmy.ml for example it works flawlessly.

Log:
```
Second failure launching org.mozilla.firefox/org.mozilla.fenix.customtabs.ExternalAppBrowserActivity, giving up
android.os.TransactionTooLargeException: data parcel size 614820 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:571)
	at android.app.IApplicationThread$Stub$Proxy.scheduleTransaction(IApplicationThread.java:2746)
	at android.app.servertransaction.ClientTransaction.schedule(ClientTransaction.java:136)
	at com.android.server.wm.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:47)
	at com.android.server.wm.ActivityTaskSupervisor.realStartActivityLocked(ActivityTaskSupervisor.java:880)
	at com.android.server.wm.RootWindowContainer.startActivityForAttachedApplicationIfNeeded(RootWindowContainer.java:2000)
	at com.android.server.wm.RootWindowContainer.$r8$lambda$auelgeOhCvbItmS_07q5VFEb1ac(Unknown Source:0)
	at com.android.server.wm.RootWindowContainer$$ExternalSyntheticLambda2.apply(Unknown Source:8)
	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:318)
	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:204)
	at com.android.internal.util.function.pooled.OmniFunction.apply(OmniFunction.java:78)
	at com.android.server.wm.ActivityRecord.forAllActivities(ActivityRecord.java:4270)
	at com.android.server.wm.WindowContainer.forAllActivities(WindowContainer.java:1430)
	at com.android.server.wm.WindowContainer.forAllActivities(WindowContainer.java:1423)
	at com.android.server.wm.RootWindowContainer.lambda$attachApplication$15$RootWindowContainer(RootWindowContainer.java:1978)
	at com.android.server.wm.RootWindowContainer$$ExternalSyntheticLambda20.accept(Unknown Source:6)
	at com.android.server.wm.Task.forAllRootTasks(Task.java:3197)
	at com.android.server.wm.WindowContainer.forAllRootTasks(WindowContainer.java:1806)
	at com.android.server.wm.WindowContainer.forAllRootTasks(WindowContainer.java:1806)
	at com.android.server.wm.WindowContainer.forAllRootTasks(WindowContainer.java:1806)
	at com.android.server.wm.WindowContainer.forAllRootTasks(WindowContainer.java:1806)
	at com.android.server.wm.WindowContainer.forAllRootTasks(WindowContainer.java:1806)
	at com.android.server.wm.WindowContainer.forAllRootTasks(WindowContainer.java:1806)
	at com.android.server.wm.WindowContainer.forAllRootTasks(WindowContainer.java:1799)
	at com.android.server.wm.RootWindowContainer.attachApplication(RootWindowContainer.java:1964)
	at com.android.server.wm.ActivityTaskManagerService$LocalService.attachApplication(ActivityTaskManagerService.java:6041)
	at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:4595)
	at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:4676)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2404)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2517)
	at android.os.Binder.execTransactInternal(Binder.java:1179)
	at android.os.Binder.execTransact(Binder.java:1143)
```

### Steps to Reproduce

1.Browse to [sopuli.xyz](https://sopuli.xyz) via Firefox based browser
2. Go to browser menu
3.select "Install"
4.Try to use the shortcut created on your home screen.

### Technical Details

* Android 13
* FF based browser

### Lemmy Instance Version

B.E 18.0, F.E unknown

### Lemmy Instance URL

https://sopuli.xyz

**Comment by lionirdeadman** [comment]
Does this still happen?

**Comment by KotoWhiskas** [comment]
Same but with feddit.de

I think it's a Firefox bug, since this doesn't happen with chromium-based browsers

**Comment by dessalines** [comment]
Stale issue.
