### ISSUE TITLE
No back-end constrainst on post.url column, causes lemmy-ui isomorphic crashing

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui#183]
Strange error at created-line
```
lemmy-ui_1  | (node:1) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: n
lemmy-ui_1  |     at onParseError (internal/url.js:259:9)
lemmy-ui_1  |     at new URL (internal/url.js:335:5)
lemmy-ui_1  |     at wt (/app/dist/js/server.js:2:15484)
lemmy-ui_1  |     at t.n.createdLine (/app/dist/js/server.js:2:285242)
lemmy-ui_1  |     at t.n.listing (/app/dist/js/server.js:2:301503)
lemmy-ui_1  |     at t.n.render (/app/dist/js/server.js:2:281952)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:210:41)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:337:37)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:307:39)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:221:20)
```

**Comment by dessalines** [comment]
Really caused by this issue: https://github.com/LemmyNet/lemmy/issues/1385
