### ISSUE TITLE
lemmy-ui returns server error

### ISSUE THREAD

**Issue by Illecors** [LemmyNet/lemmy-ui#2113]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

I'm running lemmy.cafe and it has been failing to load the UI today.

UI log:
```
Error: Input bit Array is empty
    at Sharp._createInputDescriptor (/app/node_modules/sharp/lib/input.js:56:13)
    at new Sharp (/app/node_modules/sharp/lib/constructor.js:351:29)
    at Sharp (/app/node_modules/sharp/lib/constructor.js:173:12)
    at /app/dist/js/server.js:2:1229532
    at tryCatch (/app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (/app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
    at Generator.next (/app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
UI log after disabling pictrs container:
```
[Error: Input buffer contains unsupported image format]
```

I had a similar issue after having migrated pictrs from file to object storage and the solution was to set site icon to `NULL` because it was not indexed correctly. I can load the site logo now, though, as well as the banner. Seems like it's hitting some image that is not available, I just can't figure out which one.

Jerboa works fine, so it is just the UI.

### Steps to Reproduce

1.
2.
3.
4.

### Technical Details

Latest firefox

### Lemmy Instance Version

0.18.4

### Lemmy Instance URL

https://lemmy.cafe

**Comment by KawaKode** [comment]
Hello,
I have the exact same issue, how do you set the icon to NULL ?

**Comment by Illecors** [comment]
Your instance should have an ID of 1. Just to double check - run
```
SELECT id, name, icon FROM site WHER id = 1;
```
If that's not your instance, you'll have to figure out the `ID` using `local_site` and/or `instance` tables.

If that is your instance - great!

```
UPDATE site SET icon = NULL WHERE id = 1;
```
