### ISSUE TITLE
White "server error" when visiting a comment thread in a community you've blocked

### ISSUE THREAD

**Issue by db0** [LemmyNet/lemmy-ui#2395]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

When I visit a link to a comment thread of a communit I've blocked, the lemmy-ui just shows a white page with "Server Error".

In the logs

```
lemmy-ui-1  | TypeError: Cannot read properties of undefined (reading 'comment')
lemmy-ui-1  |     at /app/dist/js/server.js:2:1161347
lemmy-ui-1  |     at a.commentTree (/app/dist/js/server.js:2:1161728)
lemmy-ui-1  |     at a.commentsTree (/app/dist/js/server.js:2:1159480)
lemmy-ui-1  |     at a.renderPostRes (/app/dist/js/server.js:2:1154679)
lemmy-ui-1  |     at a.render (/app/dist/js/server.js:2:1154925)
lemmy-ui-1  |     at P (/app/node_modules/inferno-server/dist/index.cjs.min.js:1:2338)
lemmy-ui-1  |     at P (/app/node_modules/inferno-server/dist/index.cjs.min.js:1:3216)
lemmy-ui-1  |     at P (/app/node_modules/inferno-server/dist/index.cjs.min.js:1:2444)
lemmy-ui-1  |     at P (/app/node_modules/inferno-server/dist/index.cjs.min.js:1:2544)
lemmy-ui-1  |     at P (/app/node_modules/inferno-server/dist/index.cjs.min.js:1:2444)
lemmy-1     | 2024-03-25T14:26:59.861571Z  WARN lemmy_server::root_span_builder: CouldntFindObject: Object was not found in local database
lemmy-1     |    0: lemmy_apub::fetcher::search::search_query_to_object_id_local
lemmy-1     |              at crates/apub/src/fetcher/search.rs:50
lemmy-1     |    1: lemmy_apub::api::resolve_object::resolve_object
lemmy-1     |            with data=Query(ResolveObject { q: "https://lemmy.ml/comment/4163089" }) local_user_view=None
lemmy-1     |              at crates/apub/src/api/resolve_object.rs:19
lemmy-1     |    2: lemmy_server::root_span_builder::HTTP request
lemmy-1     |            with http.method=GET http.scheme="http" http.host=lemmy:8536 http.target=/api/v3/resolve_object otel.kind="server" request_id=d442ab4f-c58a-4b16-bb0d-70f4b95f02d7
lemmy-1     |              at src/root_span_builder.rs:16
```

This has been verified by 2 other people in the matrix chat.

### Steps to Reproduce

1. Visit a post in a community, and copy the link to a comment (not the post root)
2. Block that community
3. Visit the link you saved 

### Technical Details

Firefox

### Lemmy Instance Version

0.19.3

### Lemmy Instance URL

https://lemmy.dbzer0.com

**Comment by dessalines** [comment]
Makes sense, you can't view what you've blocked.
