### ISSUE TITLE
lemmy-ui frequently crashes on lemmy.ml

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui#489]
This is causing 502 errors.

Might be related to these type errors:

```
lemmy-ui_1  | /app/node_modules/node-fetch/lib/index.js:272
lemmy-ui_1  |                           return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
lemmy-ui_1  |                                                      ^
lemmy-ui_1  | FetchError: invalid json response body at http://lemmy:8536/api/v3/user?sort=New&saved_only=false&page=1&limit=20&username=Sattaking%40lemmy.eus reason: Unexpected token E in JSON at position 0
lemmy-ui_1  |     at /app/node_modules/node-fetch/lib/index.js:272:32
lemmy-ui_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
lemmy-ui_1  |     at async Promise.all (index 0) {
lemmy-ui_1  |   type: 'invalid-json'
```

could also be:

```
lemmy-ui_1  | TypeError: Cannot read properties of null (reading 'person_blocks')
lemmy-ui_1  |     at t.o.setPersonBlock (/app/dist/js/server.js:2:668206)
lemmy-ui_1  |     at new t (/app/dist/js/server.js:2:667864)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:170:28)
```

**Comment by Tmpod** [comment]
This has apparently not been fixed. I am still getting the same error even in 0.14.3.

**Comment by dessalines** [comment]
What is the error, and how do you replicate it?

**Comment by Tmpod** [comment]
It is the same as your first one
```
FetchError: invalid json response body at http://lemmy:8536/api/v3/user?sort=New&saved_only=false&page=1&limit=20&username=poVoq%40lemmy.ml reason: Unexpected token E in JSON at position 0
    at /app/node_modules/node-fetch/lib/index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0) {
  type: 'invalid-json'
}
```

As for replication, I can't seem to find a pattern. Some users don't give any issues, but for some it always fails to show the info, always with the same error.

**Comment by dessalines** [comment]
That's a different error than this one, and is probably part of https://github.com/LemmyNet/lemmy/issues/1955
