### ISSUE TITLE
Null person_blocks breaking user pages.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui#491]
```
lemmy-ui_1  | TypeError: Cannot read properties of null (reading 'person_blocks')
lemmy-ui_1  |     at t.o.setPersonBlock (/app/dist/js/server.js:2:668206)
lemmy-ui_1  |     at new t (/app/dist/js/server.js:2:667864)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:170:28)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:221:20)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:221:20)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:303:35)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:307:39)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:221:20)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:337:37)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:221:20)
```

**Comment by mahanstreamer** [comment]
https://github.com/LemmyNet/lemmy-ui/blob/8a80b9518949cb31f7d9602b4a67d9a78e46ed59/src/shared/components/person/profile.tsx

Maybe check to see if Userservice.isntance.myUserInfo is defined and if not, just set this.state.personBlocked to false (since probably not logged in)
