### ISSUE TITLE
Errors when connecting to backend in development mode

### ISSUE THREAD

**Issue by viktorstrate** [LemmyNet/lemmy-ui#506]
### Issue Summary

When running the UI in a development, I get the following `connection refused` error.
I am not sure my computer is configured to support IPv6, that might cause the error when trying to connect to `::1:8536`.

The backend is running and serving requests on `http://localhost:8536`

```text
httpbase: http://localhost:8536
wsUri: ws://localhost:8536/api/v3/ws
isHttps: false
No JWT cookie found.
http://0.0.0.0:1234
FetchError: request to http://localhost:8536/api/v3/site? failed, reason: connect ECONNREFUSED ::1:8536
    at ClientRequest.<anonymous> (/Users/viktorstrate/Desktop/lemmy-ui/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (node:events:390:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
```

### Steps to Reproduce

1. Follow instructions for [configuring development environment from docs](https://join-lemmy.org/docs/en/contributing/local_development.html)
2. Start backend
3. Start frontend with `yarn dev`
4. Go to `http://localhost:1234` in browser
5. Browser is stuck waiting for a response and the above error is logged to the terminal

### Technical details

* Running the latest macOS
* Yarn `v1.22.17`
* Nightly rust `rustc 1.57.0-nightly`

**Comment by dayinjing** [comment]
What does the lemmy consol say? did the server every start? maybe it couldn't couldn't to postgres for some reason

**Comment by viktorstrate** [comment]
I get the following logs when starting the backend, I can also connect to it from the browser directly, although I get a blank screen.

I also checked the database, it created a bunch of tables.

<details>
<summary>Cargo logs</summary>

```text
cargo run
    Finished dev [unoptimized] target(s) in 0.98s
     Running `target/debug/lemmy_server`
  2021-11-23T18:48:10.646170Z  INFO lemmy_server::code_migrations: Running user_updates_2020_04_02
    at src/code_migrations.rs:48

  2021-11-23T18:48:10.648228Z  INFO lemmy_server::code_migrations: 0 person rows updated.
    at src/code_migrations.rs:75

  2021-11-23T18:48:10.648267Z  INFO lemmy_server::code_migrations: Running community_updates_2020_04_02
    at src/code_migrations.rs:86

  2021-11-23T18:48:10.649527Z  INFO lemmy_server::code_migrations: 0 community rows updated.
    at src/code_migrations.rs:126

  2021-11-23T18:48:10.649562Z  INFO lemmy_server::code_migrations: Running post_updates_2020_04_03
    at src/code_migrations.rs:137

  2021-11-23T18:48:10.650705Z  INFO lemmy_server::code_migrations: 0 post rows updated.
    at src/code_migrations.rs:154

  2021-11-23T18:48:10.650734Z  INFO lemmy_server::code_migrations: Running comment_updates_2020_04_03
    at src/code_migrations.rs:165

  2021-11-23T18:48:10.651776Z  INFO lemmy_server::code_migrations: 0 comment rows updated.
    at src/code_migrations.rs:182

  2021-11-23T18:48:10.651809Z  INFO lemmy_server::code_migrations: Running private_message_updates_2020_05_05
    at src/code_migrations.rs:193

  2021-11-23T18:48:10.652645Z  INFO lemmy_server::code_migrations: 0 private message rows updated.
    at src/code_migrations.rs:210

  2021-11-23T18:48:10.652681Z  INFO lemmy_server::code_migrations: Running post_thumbnail_url_updates_2020_07_27
    at src/code_migrations.rs:221

  2021-11-23T18:48:10.653466Z  INFO lemmy_server::code_migrations: 0 Post thumbnail_url rows updated.
    at src/code_migrations.rs:238

  2021-11-23T18:48:10.653496Z  INFO lemmy_server::code_migrations: Running apub_columns_2021_02_02
    at src/code_migrations.rs:246

  2021-11-23T18:48:10.655124Z  INFO lemmy_server::scheduled_tasks: Updating active site and community aggregates ...
    at src/scheduled_tasks.rs:68

Starting http server at 0.0.0.0:8536
  2021-11-23T18:48:10.656587Z  INFO actix_server::builder: Starting 16 workers
    at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.9/src/builder.rs:197

  2021-11-23T18:48:10.656681Z  INFO actix_server::server: Actix runtime found. Starting in Actix runtime
    at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.9/src/server.rs:140

  2021-11-23T18:48:10.656707Z  INFO background_jobs_actix::worker: new
    at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/background-jobs-actix-0.11.0/src/worker.rs:28
    in background_jobs_actix::worker::Worker with , worker.id: dfac193d-94ec-474f-a93d-9df7dabe363d, worker.queue: default, worker.operation.id: 7e1e12a5-da23-4266-b767-f812d37da3a9, worker.operation.name: request

  2021-11-23T18:48:10.656854Z  INFO background_jobs_actix::worker: close, time.busy: 71.7µs, time.idle: 81.0µs
    at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/background-jobs-actix-0.11.0/src/worker.rs:28
    in background_jobs_actix::worker::Worker with , worker.id: dfac193d-94ec-474f-a93d-9df7dabe363d, worker.queue: default, worker.operation.id: 7e1e12a5-da23-4266-b767-f812d37da3a9, worker.operation.name: request

  2021-11-23T18:48:10.656965Z  INFO background_jobs_actix::worker: new
    at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/background-jobs-actix-0.11.0/src/worker.rs:28
    in background_jobs_actix::worker::Worker with , worker.id: 2daa40ed-021f-4bbf-8b31-512db5c64189, worker.queue: default, worker.operation.id: b5584510-e976-43a9-bc96-5d36ad215a0f, worker.operation.name: request

  2021-11-23T18:48:10.657042Z  INFO background_jobs_actix::worker: close, time.busy: 22.8µs, time.idle: 55.0µs
    at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/background-jobs-actix-0.11.0/src/worker.rs:28
    in background_jobs_actix::worker::Worker with , worker.id: 2daa40ed-021f-4bbf-8b31-512db5c64189, worker.queue: default, worker.operation.id: b5584510-e976-43a9-bc96-5d36ad215a0f, worker.operation.name: request

  2021-11-23T18:48:10.657134Z  INFO background_jobs_actix::worker: new
    at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/background-jobs-actix-0.11.0/src/worker.rs:28
    in background_jobs_actix::worker::Worker with , worker.id: 8da8a8a9-a753-499f-bc97-215d7ddea98a, worker.queue: default, worker.operation.id: 25a4ce13-8e02-425f-8564-85e59b15a450, worker.operation.name: request

  2021-11-23T18:48:10.657209Z  INFO background_jobs_actix::worker: close, time.busy: 21.4µs, time.idle: 54.2µs
    at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/background-jobs-actix-0.11.0/src/worker.rs:28
    in background_jobs_actix::worker::Worker with , worker.id: 8da8a8a9-a753-499f-bc97-215d7ddea98a, worker.queue: default, worker.operation.id: 25a4ce13-8e02-425f-8564-85e59b15a450, worker.operation.name: request

  2021-11-23T18:48:10.657294Z  INFO background_jobs_actix::worker: new
    at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/background-jobs-actix-0.11.0/src/worker.rs:28
    in background_jobs_actix::worker::Worker with , worker.id: 2d50dcf9-8eee-48ab-92d9-2833f6e2a2f1, worker.queue: default, worker.operation.id: 0f91f6ba-26ae-4311-bbb4-3218b0bfb8cb, worker.operation.name: request

  2021-11-23T18:48:10.657365Z  INFO background_jobs_actix::worker: close, time.busy: 20.8µs, time.idle: 50.6µs
    at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/background-jobs-actix-0.11.0/src/worker.rs:28
    in background_jobs_actix::worker::Worker with , worker.id: 2d50dcf9-8eee-48ab-92d9-2833f6e2a2f1, worker.queue: default, worker.operation.id: 0f91f6ba-26ae-4311-bbb4-3218b0bfb8cb, worker.operation.name: request

federation enabled, host is lemmy-alpha
federation enabled, host is lemmy-alpha
federation enabled, host is lemmy-alpha
  2021-11-23T18:48:10.679260Z  INFO lemmy_server::scheduled_tasks: Done.
    at src/scheduled_tasks.rs:92

  2021-11-23T18:48:10.679322Z  INFO lemmy_server::scheduled_tasks: Reindexing table concurrently post_aggregates ...
    at src/scheduled_tasks.rs:53

federation enabled, host is lemmy-alpha
federation enabled, host is lemmy-alpha
federation enabled, host is lemmy-alpha
federation enabled, host is lemmy-alpha
  2021-11-23T18:48:10.719798Z  INFO lemmy_server::scheduled_tasks: Done.
    at src/scheduled_tasks.rs:56

  2021-11-23T18:48:10.719836Z  INFO lemmy_server::scheduled_tasks: Reindexing table concurrently comment_aggregates ...
    at src/scheduled_tasks.rs:53

federation enabled, host is lemmy-alpha
  2021-11-23T18:48:10.730484Z  INFO lemmy_server::scheduled_tasks: Done.
    at src/scheduled_tasks.rs:56

  2021-11-23T18:48:10.730530Z  INFO lemmy_server::scheduled_tasks: Reindexing table concurrently community_aggregates ...
    at src/scheduled_tasks.rs:53

federation enabled, host is lemmy-alpha
  2021-11-23T18:48:10.740494Z  INFO lemmy_server::scheduled_tasks: Done.
    at src/scheduled_tasks.rs:56

federation enabled, host is lemmy-alpha
  2021-11-23T18:48:10.742241Z  INFO lemmy_server::scheduled_tasks: Clearing old activities...
    at src/scheduled_tasks.rs:61

  2021-11-23T18:48:10.744842Z  INFO lemmy_server::scheduled_tasks: Done.
    at src/scheduled_tasks.rs:63

federation enabled, host is lemmy-alpha
federation enabled, host is lemmy-alpha
federation enabled, host is lemmy-alpha
federation enabled, host is lemmy-alpha
federation enabled, host is lemmy-alpha
federation enabled, host is lemmy-alpha
```

</details>

**Comment by dessalines** [comment]
This works fine? http://localhost:8536/api/v3/site

I have no idea then, lemmy server doesn't support IPv6, and your browser seems to be trying to do that?

**Comment by viktorstrate** [comment]
I get back the following when I visit that link: 

```
{"site_view":null,"admins":[],"banned":[],"online":0,"version":"unknown version","my_user":null,"federated_instances":{"linked":[],"allowed":null,"blocked":null}}
```

No, it's not my browser since the error is printed in the terminal that runs webpack `$ yarn dev`.

**Comment by dessalines** [comment]
Okay then something is broken, because your site_view should not be null. There are too many permutations and possibilities for errors and misconfigurations with local dev setups, so I can't help there. 

If you use the docker development setup, I can probably help: https://join-lemmy.org/docs/en/contributing/docker_development.html

**Comment by dayinjing** [comment]
What version of node are you running? I had to lock it at version 16. I can't remember if this was the problem I was running into but I think it was.

**Comment by viktorstrate** [comment]
@dayinjing

```sh
$ node --version
v17.0.1
```

**Comment by dessalines** [comment]
Its a back-end problem, your site_view should not be null.

**Comment by viktorstrate** [comment]
@dessalines okay, the only configurations I did before running `cargo run` was to make some changes to `config/config.hjson`, this is my modified version.

```hjson
{
  hostname: lemmy-alpha
  federation: {
    enabled: true
  }
  database: {
    # Username to connect to postgres
    user: "postgres"
    # Password to connect to postgres
    password: "postgres"
    # Host where postgres is running
    host: "localhost"
    # Port where postgres can be accessed
    port: 5432
    # Name of the postgres database for lemmy
    database: "lemmy"
    # Maximum number of active sql connections
    pool_size: 5
  }
}
```

I have no prior experience with lemmy, so I might have missed somthing obvious.
I've posted a full log of `cargo run` earlier, maybe that says anything?

**Comment by bigOconstant** [comment]
> 

here is mine

```
{
  # for more info about the config, check out the documentation
  # https://join-lemmy.org/docs/en/administration/configuration.html

  setup: {
    # username for the admin user
    admin_username: "lemmy"
    # password for the admin user
    admin_password: "lemmy"
    # name of the site (can be changed later)
    site_name: "lemmy-test"
  }

  # the domain name of your instance (eg "lemmy.ml")
  hostname: "http://localhost:1234"
  # address where lemmy should listen for incoming requests
  bind: "0.0.0.0"
  # port where lemmy should listen for incoming requests
  port: 8536
  # json web token for authorization between server and client
  jwt_secret: "123456789"
  # settings related to the postgresql database
  # address where pictrs is available
  pictrs_url: "http://pictrs:8080"
  database: {
    # name of the postgres database for lemmy
    database: "lemmy"
    # username to connect to postgres
    user: "lemmy"
    # password to connect to postgres
    password: "password"
    # host where postgres is running
    host: "postgres"
    # port where postgres can be accessed
    port: 5432
    # maximum number of active sql connections
    pool_size: 5
  }
#  # optional: email sending configuration
#  email: {
#    # hostname and port of the smtp server
#    smtp_server: ""
#    # login name for smtp server
#    smtp_login: ""
#    # password to login to the smtp server
#    smtp_password: ""
#    # address to send emails from, eg "noreply@your-instance.com"
#    smtp_from_address: ""
#    # whether or not smtp connections should use tls
#    use_tls: true
#  }
}
```

**Comment by Nutomic** [comment]
You could try to have the backend connect to 127.0.0.1 instead of localhost. Not sure how it works in debug mode, maybe `LEMMY_INTERNAL_HOST=127.0.0.1:8536` works, otherwise you might have to modify the source code.

**Comment by viktorstrate** [comment]
@Nutomic That fixed the error, but not I get a new one. Somthing about the JSON response from the server is malformed.
It mentions `invalid password`, I'm sorry if I'm missing somthing completely obvious. I'm mostly using the config file @bigOconstant provided.

The browser just hangs waiting for a response when I visit `localhost:1234`

<details>
<summary>UI Logs</summary>

```sh
yarn dev
yarn run v1.22.17
$ yarn start
$ yarn build:dev --watch
$ yarn clean && node generate_translations.js
$ yarn run rimraf dist
$ /Users/viktorstrate/Desktop/lemmy-ui/node_modules/.bin/rimraf dist
$ webpack --mode=development --watch
[RunNodeWebpackPlugin] Starting node script: js/server.js
Inferno is in development mode.
Inferno is in development mode.
Inferno is in development mode.
assets by path assets/css/ 2.14 MiB
  assets by path assets/css/themes/*.css 2.11 MiB 13 assets
  assets by path assets/css/themes/*.scss 29.1 KiB
    asset assets/css/themes/_variables.bootstra_386-tmp.scss 22.3 KiB [emitted] [from: src/assets/css/themes/_variables.bootstra_386-tmp.scss] [copied]
    asset assets/css/themes/_variables.darkly.scss 3.13 KiB [emitted] [from: src/assets/css/themes/_variables.darkly.scss] [copied]
    asset assets/css/themes/_variables.i386.scss 1.07 KiB [emitted] [from: src/assets/css/themes/_variables.i386.scss] [copied]
    asset assets/css/themes/_variables.vaporwave-dark.scss 1.01 KiB [emitted] [from: src/assets/css/themes/_variables.vaporwave-dark.scss] [copied]
    asset assets/css/themes/_variables.litely.scss 950 bytes [emitted] [from: src/assets/css/themes/_variables.litely.scss] [copied]
    asset assets/css/themes/_variables.vaporwave-light.scss 661 bytes [emitted] [from: src/assets/css/themes/_variables.vaporwave-light.scss] [copied]
  asset assets/css/main.css 5.34 KiB [emitted] [from: src/assets/css/main.css] [copied]
assets by path assets/icons/ 89.5 KiB 10 assets
assets by chunk 1.62 MiB (name: main)
  asset js/server.js 1.61 MiB [emitted] [big] (name: main)
  asset styles/styles.css 18.6 KiB [emitted] (name: main)
asset assets/manifest.webmanifest 1.09 KiB [emitted] [from: src/assets/manifest.webmanifest] [copied]
Entrypoint main [big] 1.62 MiB = styles/styles.css 18.6 KiB js/server.js 1.61 MiB
cached modules 615 KiB (javascript) 16.8 KiB (css/mini-extract) 937 bytes (runtime) [cached] 150 modules
javascript modules 549 KiB 46 modules
webpack 5.64.2 compiled successfully in 2697 ms

assets by path assets/css/ 2.14 MiB
  assets by path assets/css/themes/*.css 2.11 MiB 13 assets
  assets by path assets/css/themes/*.scss 29.1 KiB
    asset assets/css/themes/_variables.bootstra_386-tmp.scss 22.3 KiB [compared for emit] [from: src/assets/css/themes/_variables.bootstra_386-tmp.scss] [copied]
    asset assets/css/themes/_variables.darkly.scss 3.13 KiB [compared for emit] [from: src/assets/css/themes/_variables.darkly.scss] [copied]
    asset assets/css/themes/_variables.i386.scss 1.07 KiB [compared for emit] [from: src/assets/css/themes/_variables.i386.scss] [copied]
    asset assets/css/themes/_variables.vaporwave-dark.scss 1.01 KiB [compared for emit] [from: src/assets/css/themes/_variables.vaporwave-dark.scss] [copied]
    asset assets/css/themes/_variables.litely.scss 950 bytes [compared for emit] [from: src/assets/css/themes/_variables.litely.scss] [copied]
    asset assets/css/themes/_variables.vaporwave-light.scss 661 bytes [compared for emit] [from: src/assets/css/themes/_variables.vaporwave-light.scss] [copied]
  asset assets/css/main.css 5.34 KiB [compared for emit] [from: src/assets/css/main.css] [copied]
assets by path assets/icons/ 89.5 KiB 10 assets
assets by status 4.12 MiB [emitted]
  asset js/client.js 4.1 MiB [emitted] [big] (name: main)
  asset styles/styles.css 18.6 KiB [emitted] [compared for emit] (name: main)
asset assets/manifest.webmanifest 1.09 KiB [compared for emit] [from: src/assets/manifest.webmanifest] [copied]
Entrypoint main [big] 4.12 MiB = styles/styles.css 18.6 KiB js/client.js 4.1 MiB
cached modules 2.86 MiB (javascript) 16.8 KiB (css/mini-extract) 1.25 KiB (runtime) [cached] 692 modules
javascript modules 549 KiB 46 modules
webpack 5.64.2 compiled successfully in 3015 ms
httpbase: http://127.0.0.1:8536
wsUri: ws://127.0.0.1:8536/api/v3/ws
isHttps: false
No JWT cookie found.
http://0.0.0.0:1234
FetchError: invalid json response body at http://127.0.0.1:8536/api/v3/site? reason: Unexpected number in JSON at position 31
    at /Users/viktorstrate/Desktop/lemmy-ui/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'invalid-json'
}
```

</details>

<details>
<summary>Backend logs</summary>

```sh
cargo run
    Finished dev [unoptimized] target(s) in 1.17s
     Running `target/debug/lemmy_server`
  2021-11-25T15:44:23.132021Z  INFO lemmy_server::code_migrations: Running user_updates_2020_04_02
    at src/code_migrations.rs:48

  2021-11-25T15:44:23.134289Z  INFO lemmy_server::code_migrations: 0 person rows updated.
    at src/code_migrations.rs:75

  2021-11-25T15:44:23.134331Z  INFO lemmy_server::code_migrations: Running community_updates_2020_04_02
    at src/code_migrations.rs:86

  2021-11-25T15:44:23.135797Z  INFO lemmy_server::code_migrations: 0 community rows updated.
    at src/code_migrations.rs:126

  2021-11-25T15:44:23.135830Z  INFO lemmy_server::code_migrations: Running post_updates_2020_04_03
    at src/code_migrations.rs:137

  2021-11-25T15:44:23.137182Z  INFO lemmy_server::code_migrations: 0 post rows updated.
    at src/code_migrations.rs:154

  2021-11-25T15:44:23.137216Z  INFO lemmy_server::code_migrations: Running comment_updates_2020_04_03
    at src/code_migrations.rs:165

  2021-11-25T15:44:23.139744Z  INFO lemmy_server::code_migrations: 0 comment rows updated.
    at src/code_migrations.rs:182

  2021-11-25T15:44:23.139909Z  INFO lemmy_server::code_migrations: Running private_message_updates_2020_05_05
    at src/code_migrations.rs:193

  2021-11-25T15:44:23.141815Z  INFO lemmy_server::code_migrations: 0 private message rows updated.
    at src/code_migrations.rs:210

  2021-11-25T15:44:23.141891Z  INFO lemmy_server::code_migrations: Running post_thumbnail_url_updates_2020_07_27
    at src/code_migrations.rs:221

  2021-11-25T15:44:23.143152Z  INFO lemmy_server::code_migrations: 0 Post thumbnail_url rows updated.
    at src/code_migrations.rs:238

  2021-11-25T15:44:23.143240Z  INFO lemmy_server::code_migrations: Running apub_columns_2021_02_02
    at src/code_migrations.rs:246

  2021-11-25T15:44:23.145497Z  INFO lemmy_server::scheduled_tasks: Updating active site and community aggregates ...
    at src/scheduled_tasks.rs:68

Starting http server at 0.0.0.0:8536
  2021-11-25T15:44:23.147793Z  INFO actix_server::builder: Starting 16 workers
    at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.9/src/builder.rs:197

  2021-11-25T15:44:23.147909Z  INFO actix_server::server: Actix runtime found. Starting in Actix runtime
    at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.9/src/server.rs:140

  2021-11-25T15:44:23.147940Z  INFO background_jobs_actix::worker: new
    at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/background-jobs-actix-0.11.0/src/worker.rs:28
    in background_jobs_actix::worker::Worker with , worker.id: 0f9488aa-0153-4ab8-8759-7d6f13047e87, worker.queue: default, worker.operation.id: e6220608-4305-49b8-9a6c-bbf766a206f4, worker.operation.name: request

  2021-11-25T15:44:23.148095Z  INFO background_jobs_actix::worker: close, time.busy: 84.9µs, time.idle: 76.2µs
    at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/background-jobs-actix-0.11.0/src/worker.rs:28
    in background_jobs_actix::worker::Worker with , worker.id: 0f9488aa-0153-4ab8-8759-7d6f13047e87, worker.queue: default, worker.operation.id: e6220608-4305-49b8-9a6c-bbf766a206f4, worker.operation.name: request

  2021-11-25T15:44:23.148225Z  INFO background_jobs_actix::worker: new
    at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/background-jobs-actix-0.11.0/src/worker.rs:28
    in background_jobs_actix::worker::Worker with , worker.id: d39b7130-92a9-4eab-8f8e-95248902cb75, worker.queue: default, worker.operation.id: 1eea5661-1c83-4fb4-b45d-a36535e1f128, worker.operation.name: request

  2021-11-25T15:44:23.148313Z  INFO background_jobs_actix::worker: close, time.busy: 29.1µs, time.idle: 59.2µs
    at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/background-jobs-actix-0.11.0/src/worker.rs:28
    in background_jobs_actix::worker::Worker with , worker.id: d39b7130-92a9-4eab-8f8e-95248902cb75, worker.queue: default, worker.operation.id: 1eea5661-1c83-4fb4-b45d-a36535e1f128, worker.operation.name: request

  2021-11-25T15:44:23.148396Z  INFO background_jobs_actix::worker: new
    at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/background-jobs-actix-0.11.0/src/worker.rs:28
    in background_jobs_actix::worker::Worker with , worker.id: 3de0aead-7645-4234-aca6-755159584449, worker.queue: default, worker.operation.id: 0b79ddce-304c-40ed-af7e-c4935aeb584a, worker.operation.name: request

  2021-11-25T15:44:23.148465Z  INFO background_jobs_actix::worker: close, time.busy: 21.7µs, time.idle: 46.8µs
    at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/background-jobs-actix-0.11.0/src/worker.rs:28
    in background_jobs_actix::worker::Worker with , worker.id: 3de0aead-7645-4234-aca6-755159584449, worker.queue: default, worker.operation.id: 0b79ddce-304c-40ed-af7e-c4935aeb584a, worker.operation.name: request

  2021-11-25T15:44:23.148576Z  INFO background_jobs_actix::worker: new
    at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/background-jobs-actix-0.11.0/src/worker.rs:28
    in background_jobs_actix::worker::Worker with , worker.id: 24946c77-2982-4aaa-bf25-7c4243ac28ee, worker.queue: default, worker.operation.id: 15e0da0a-4bc6-4c59-81f1-92acca4ad1bc, worker.operation.name: request

  2021-11-25T15:44:23.148666Z  INFO background_jobs_actix::worker: close, time.busy: 24.8µs, time.idle: 68.0µs
    at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/background-jobs-actix-0.11.0/src/worker.rs:28
    in background_jobs_actix::worker::Worker with , worker.id: 24946c77-2982-4aaa-bf25-7c4243ac28ee, worker.queue: default, worker.operation.id: 15e0da0a-4bc6-4c59-81f1-92acca4ad1bc, worker.operation.name: request

  2021-11-25T15:44:23.166065Z  INFO lemmy_server::scheduled_tasks: Done.
    at src/scheduled_tasks.rs:92

  2021-11-25T15:44:23.166154Z  INFO lemmy_server::scheduled_tasks: Reindexing table concurrently post_aggregates ...
    at src/scheduled_tasks.rs:53

  2021-11-25T15:44:23.219369Z  INFO lemmy_server::scheduled_tasks: Done.
    at src/scheduled_tasks.rs:56

  2021-11-25T15:44:23.219400Z  INFO lemmy_server::scheduled_tasks: Reindexing table concurrently comment_aggregates ...
    at src/scheduled_tasks.rs:53

  2021-11-25T15:44:23.230495Z  INFO lemmy_server::scheduled_tasks: Done.
    at src/scheduled_tasks.rs:56

  2021-11-25T15:44:23.230552Z  INFO lemmy_server::scheduled_tasks: Reindexing table concurrently community_aggregates ...
    at src/scheduled_tasks.rs:53

  2021-11-25T15:44:23.244493Z  INFO lemmy_server::scheduled_tasks: Done.
    at src/scheduled_tasks.rs:56

  2021-11-25T15:44:23.246504Z  INFO lemmy_server::scheduled_tasks: Clearing old activities...
    at src/scheduled_tasks.rs:61

  2021-11-25T15:44:23.249702Z  INFO lemmy_server::scheduled_tasks: Done.
    at src/scheduled_tasks.rs:63

  2021-11-25T15:44:36.519564Z  INFO tracing_actix_web::root_span_builder: new
    at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-actix-web-0.5.0-beta.2/src/root_span_builder.rs:40
    in tracing_actix_web::root_span_builder::HTTP request with , http.method: GET, http.route: /api/v3/site, http.flavor: 1.1, http.scheme: http, http.host: 0.0.0.0:1234, http.client_ip: 127.0.0.1:55870, http.user_agent: node-fetch/1.0 (+https://github.com/bitinn/node-fetch), http.target: /api/v3/site?, otel.kind: "server", request_id: 39c46e39-6c73-422e-aa50-014952396901

  2021-11-25T15:44:36.530946Z  WARN tracing_actix_web::middleware: Error encountered while processing the incoming HTTP request: LemmyError { inner: {"error":"invalid_password"}, context: SpanTrace [{ target: "tracing_actix_web::root_span_builder", name: "HTTP request", fields: "http.method=GET http.route=/api/v3/site http.flavor=1.1 http.scheme=http http.host=0.0.0.0:1234 http.client_ip=127.0.0.1:55870 http.user_agent=node-fetch/1.0 (+https://github.com/bitinn/node-fetch) http.target=/api/v3/site? otel.kind=\"server\" request_id=39c46e39-6c73-422e-aa50-014952396901", file: "/Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-actix-web-0.5.0-beta.2/src/root_span_builder.rs", line: 40 }] }
    at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-actix-web-0.5.0-beta.2/src/middleware.rs:256
    in tracing_actix_web::root_span_builder::HTTP request with , http.method: GET, http.route: /api/v3/site, http.flavor: 1.1, http.scheme: http, http.host: 0.0.0.0:1234, http.client_ip: 127.0.0.1:55870, http.user_agent: node-fetch/1.0 (+https://github.com/bitinn/node-fetch), http.target: /api/v3/site?, otel.kind: "server", request_id: 39c46e39-6c73-422e-aa50-014952396901, exception.message: {"error":"invalid_password"}   0: tracing_actix_web::root_span_builder::HTTP request
           with http.method=GET http.route=/api/v3/site http.flavor=1.1 http.scheme=http http.host=0.0.0.0:1234 http.client_ip=127.0.0.1:55870 http.user_agent=node-fetch/1.0 (+https://github.com/bitinn/node-fetch) http.target=/api/v3/site? otel.kind="server" request_id=39c46e39-6c73-422e-aa50-014952396901
             at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-actix-web-0.5.0-beta.2/src/root_span_builder.rs:40, exception.details: LemmyError { inner: {"error":"invalid_password"}, context: SpanTrace [{ target: "tracing_actix_web::root_span_builder", name: "HTTP request", fields: "http.method=GET http.route=/api/v3/site http.flavor=1.1 http.scheme=http http.host=0.0.0.0:1234 http.client_ip=127.0.0.1:55870 http.user_agent=node-fetch/1.0 (+https://github.com/bitinn/node-fetch) http.target=/api/v3/site? otel.kind=\"server\" request_id=39c46e39-6c73-422e-aa50-014952396901", file: "/Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-actix-web-0.5.0-beta.2/src/root_span_builder.rs", line: 40 }] }, http.status_code: 400, otel.status_code: "OK"

  2021-11-25T15:44:36.531340Z  INFO tracing_actix_web::root_span_builder: close, time.busy: 2.51ms, time.idle: 9.27ms
    at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-actix-web-0.5.0-beta.2/src/root_span_builder.rs:40
    in tracing_actix_web::root_span_builder::HTTP request with , http.method: GET, http.route: /api/v3/site, http.flavor: 1.1, http.scheme: http, http.host: 0.0.0.0:1234, http.client_ip: 127.0.0.1:55870, http.user_agent: node-fetch/1.0 (+https://github.com/bitinn/node-fetch), http.target: /api/v3/site?, otel.kind: "server", request_id: 39c46e39-6c73-422e-aa50-014952396901, exception.message: {"error":"invalid_password"}   0: tracing_actix_web::root_span_builder::HTTP request
           with http.method=GET http.route=/api/v3/site http.flavor=1.1 http.scheme=http http.host=0.0.0.0:1234 http.client_ip=127.0.0.1:55870 http.user_agent=node-fetch/1.0 (+https://github.com/bitinn/node-fetch) http.target=/api/v3/site? otel.kind="server" request_id=39c46e39-6c73-422e-aa50-014952396901
             at /Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-actix-web-0.5.0-beta.2/src/root_span_builder.rs:40, exception.details: LemmyError { inner: {"error":"invalid_password"}, context: SpanTrace [{ target: "tracing_actix_web::root_span_builder", name: "HTTP request", fields: "http.method=GET http.route=/api/v3/site http.flavor=1.1 http.scheme=http http.host=0.0.0.0:1234 http.client_ip=127.0.0.1:55870 http.user_agent=node-fetch/1.0 (+https://github.com/bitinn/node-fetch) http.target=/api/v3/site? otel.kind=\"server\" request_id=39c46e39-6c73-422e-aa50-014952396901", file: "/Users/viktorstrate/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-actix-web-0.5.0-beta.2/src/root_span_builder.rs", line: 40 }] }, http.status_code: 400, otel.status_code: "OK"
```

</details>

**Comment by Kradyz** [comment]
I just struggled with this too. In my case (and possibly yours too) the error was caused by the /etc/hosts file containing the following IPv6 mapping:

`::1    localhost`


If you did not change the default configuration, the invalid_password may have been triggered by trying to create an admin with a  password was less than 10 characters long.

**Comment by dessalines** [comment]
We can re-open if there's a specific issue that still exists.

**Comment by sam365724** [comment]
Might be the root cause: https://github.com/LemmyNet/lemmy/issues/2467
